[package]
name = "FRCScouter"
version = "0.0.1"
authors = ["pizzajess"]
edition = "2018"

[dependencies]
ws = "0.9.1"
rocket = "0.4.2"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["json", "serve"]
