name: Rust

on: [push]

jobs:
  build:
    runs-on: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
